datasets:
  real_id: 02210b47a0534666b0462a175bf2af9d
  synthetic_id: df83f93a6c92432394418fbcc046725c
hyperparams:
  aug_copies: 4
  batch_size: 8
  blank_bias_init: -2.0
  brightness_delta: 0.1
  epochs: 30
  lr: 0.001
  noise_sigma: 0.02
  num_layers: 2
  patience: 5
  rnn_hidden: 256
  rotation_max: 7.0
  weight_decay: 0.0001
