datasets:
  id: af1b2cd0017a48f593eb29bd5dcbae61

queue_name: ofek
hpo_storage: outputs/hpo_pretrain.db
manifest: outputs/synthetic/manifest.csv

hyperparams:
  batch_size: 8
  blank_bias_init: -2.0
  num_layers: 1
  pretrain_epochs: 36
  pretrain_lr: 0.000736011
  rnn_hidden: 256
  weight_decay: 0.0001
